/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TodoRouteImport } from './routes/todo'
import { Route as ReminderRouteImport } from './routes/reminder'
import { Route as HabitTrackerRouteImport } from './routes/habit-tracker'
import { Route as IndexRouteImport } from './routes/index'

const TodoRoute = TodoRouteImport.update({
  id: '/todo',
  path: '/todo',
  getParentRoute: () => rootRouteImport,
} as any)
const ReminderRoute = ReminderRouteImport.update({
  id: '/reminder',
  path: '/reminder',
  getParentRoute: () => rootRouteImport,
} as any)
const HabitTrackerRoute = HabitTrackerRouteImport.update({
  id: '/habit-tracker',
  path: '/habit-tracker',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/habit-tracker': typeof HabitTrackerRoute
  '/reminder': typeof ReminderRoute
  '/todo': typeof TodoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/habit-tracker': typeof HabitTrackerRoute
  '/reminder': typeof ReminderRoute
  '/todo': typeof TodoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/habit-tracker': typeof HabitTrackerRoute
  '/reminder': typeof ReminderRoute
  '/todo': typeof TodoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/habit-tracker' | '/reminder' | '/todo'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/habit-tracker' | '/reminder' | '/todo'
  id: '__root__' | '/' | '/habit-tracker' | '/reminder' | '/todo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HabitTrackerRoute: typeof HabitTrackerRoute
  ReminderRoute: typeof ReminderRoute
  TodoRoute: typeof TodoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/todo': {
      id: '/todo'
      path: '/todo'
      fullPath: '/todo'
      preLoaderRoute: typeof TodoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reminder': {
      id: '/reminder'
      path: '/reminder'
      fullPath: '/reminder'
      preLoaderRoute: typeof ReminderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/habit-tracker': {
      id: '/habit-tracker'
      path: '/habit-tracker'
      fullPath: '/habit-tracker'
      preLoaderRoute: typeof HabitTrackerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HabitTrackerRoute: HabitTrackerRoute,
  ReminderRoute: ReminderRoute,
  TodoRoute: TodoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
