/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as TodoRouteImport } from './routes/todo'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReminderRouteImport } from './routes/reminder'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HabitTrackerRouteImport } from './routes/habit-tracker'
import { Route as GoalsRouteImport } from './routes/goals'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FocusRouteImport } from './routes/focus'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const TodoRoute = TodoRouteImport.update({
  id: '/todo',
  path: '/todo',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReminderRoute = ReminderRouteImport.update({
  id: '/reminder',
  path: '/reminder',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HabitTrackerRoute = HabitTrackerRouteImport.update({
  id: '/habit-tracker',
  path: '/habit-tracker',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsRoute = GoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FocusRoute = FocusRouteImport.update({
  id: '/focus',
  path: '/focus',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agent': typeof AgentRoute
  '/focus': typeof FocusRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/goals': typeof GoalsRoute
  '/habit-tracker': typeof HabitTrackerRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/reminder': typeof ReminderRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/todo': typeof TodoRoute
  '/verify-email': typeof VerifyEmailRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agent': typeof AgentRoute
  '/focus': typeof FocusRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/goals': typeof GoalsRoute
  '/habit-tracker': typeof HabitTrackerRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/reminder': typeof ReminderRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/todo': typeof TodoRoute
  '/verify-email': typeof VerifyEmailRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agent': typeof AgentRoute
  '/focus': typeof FocusRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/goals': typeof GoalsRoute
  '/habit-tracker': typeof HabitTrackerRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/reminder': typeof ReminderRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/todo': typeof TodoRoute
  '/verify-email': typeof VerifyEmailRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/agent'
    | '/focus'
    | '/forgot-password'
    | '/goals'
    | '/habit-tracker'
    | '/login'
    | '/profile'
    | '/reminder'
    | '/reset-password'
    | '/signup'
    | '/todo'
    | '/verify-email'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/agent'
    | '/focus'
    | '/forgot-password'
    | '/goals'
    | '/habit-tracker'
    | '/login'
    | '/profile'
    | '/reminder'
    | '/reset-password'
    | '/signup'
    | '/todo'
    | '/verify-email'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/agent'
    | '/focus'
    | '/forgot-password'
    | '/goals'
    | '/habit-tracker'
    | '/login'
    | '/profile'
    | '/reminder'
    | '/reset-password'
    | '/signup'
    | '/todo'
    | '/verify-email'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AgentRoute: typeof AgentRoute
  FocusRoute: typeof FocusRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GoalsRoute: typeof GoalsRoute
  HabitTrackerRoute: typeof HabitTrackerRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  ReminderRoute: typeof ReminderRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  TodoRoute: typeof TodoRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/todo': {
      id: '/todo'
      path: '/todo'
      fullPath: '/todo'
      preLoaderRoute: typeof TodoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reminder': {
      id: '/reminder'
      path: '/reminder'
      fullPath: '/reminder'
      preLoaderRoute: typeof ReminderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/habit-tracker': {
      id: '/habit-tracker'
      path: '/habit-tracker'
      fullPath: '/habit-tracker'
      preLoaderRoute: typeof HabitTrackerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals': {
      id: '/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/focus': {
      id: '/focus'
      path: '/focus'
      fullPath: '/focus'
      preLoaderRoute: typeof FocusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AgentRoute: AgentRoute,
  FocusRoute: FocusRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GoalsRoute: GoalsRoute,
  HabitTrackerRoute: HabitTrackerRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  ReminderRoute: ReminderRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  TodoRoute: TodoRoute,
  VerifyEmailRoute: VerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
